Annahme einer bedeutenden Bekleidung
------------------------------------

Die Geschichte erzählt, dass alles dort dunkel war, und Jurgen konnte niemanden
sehen. Aber die Höhle erstreckte sich gerade aus, und unten, am fernen Ende,
glühte ein Lichtschein. Jurgen ging und ging, und so kam er nahe zu einem
Zentauren, und das erstaunte ihn nicht wenig, denn er wusste, dass Zentauren
imaginäre Kreaturen waren.

Sicherlich waren sie sonderbare anzuschauen: Denn hier war der Körper eines
feinen braunen Pferdes, und aus seinen Schultern sproß der sonnengebräunte
Körper eines jungen Kerls, der Jurgen mit tiefgründigen und nicht
unfreundlichen Augen ansah. Der Zentaus lag neben einem Feuer von Zedern- und
Wacholderholz, neben ihm war eine Schale mit einer Flüssigkeit, mit der er
seine Hufe benetzte. Dieses Zeug verwandelte, als der Zentaur es mit seinen
Fingern einmassierte, das Aussehen seiner Hufe zu Gold.

``Heil Dir, mein Freund,'' sagte Jurgen, ``wenn Du ein Werk Gottes bist.''

``Deine Vorbedingung ist nicht gut Griechisch,'' bemerkte der Zentaur, ``denn
in Hellas hatten wir nicht solche Bedenken. Daneben ist es weniger meine
Herkunft, als meine Bestimmung, die für Dich wichtig ist.''

``Nun gut, mein Freund, und wohin wirst Du gehen?''

``In den Garten zwischen Dämmerung und Morgenröte, Jurgen.''

``Das ist wahrlich ein feiner Name für einen Garten! Und es ist ein Platz, den
ich mit Freuden sehen würde.''

``Hinauf auf meinen Rücken, Jurgen, und ich werde Dich dorthin bringen,'' sagt
der Zentaur und erhob sich auf seine Füße. Dann sagte der Zentaur, als der
Pfnadleiher zögerte: ``Denn, wie Du wissen musst, es gibt keinen anderen Weg.
Denn dieser Garten existiert nicht, und existierte niemals in dem, was die
Menschen humorvoll das wahre Leben nennen, und nur imaginäre Kreaturen, so wie
ich, können ihn betreten.''

``Das klingt einleuchtend,'' stellte Jurgen fest, ``aber wie es sich begibt,
bin ich auf der Suche nach meiner Frau, die, wie ich vermute, von einem Teufel
verschleppt wurde, die Arme!''

Und Jurgen begann dem Zentauren zu erklären, was sich begeben hatte.

Der Zentaur lachte. ``Es mag sein, dass das der Grund dafür ist, dass ich hier
bin. Es gibt, in jedem Fall, nur einen Behelf in dieser Sache. Über allen
Teufeln, und über allen Göttern, wie man mir sagt, aber sicherlich über allen
Zentauren, steht die Macht Koshcheis, der Untoten, der die Dinge machte, wie
sie sind.''

``Es ist nicht immer förderlich,'' wandte Jurgen ein, ``von Koshchei zu
sprechen. Es scheint besonders wenig wünschenswert an einem düsteren Ort wie
diesem.''

``Nichtsdestotrotz vermute ich, dass Du Dich an ihn wenden musst, um
Gerechtigkeit zu erlangen.''

``Ich würde es vorziehen, das nicht zu tun,'' sagte Jurgen in ungerührter
Offenheit.

``Du hast mein vollstes Verständnis, aber es ist keine Frage von Vorzügen,
wenn es um Koshchei geht. Denkst Du etwa, dass ich aus freien Stücken an diesem
unterirdischen Ort friere? Und dass ich Deinen Namen zufällig kannte?''

Jurgen fürchtete sich ein wenig. ``Gut, gut. Aber es ist gewöhnlich ein
teuflisches Ding, zu tun, was ein Mann tun muss. Nun denn, kann ich zu
Koshchei kommen?''

``Auf indirektem Wege,'' sagte der Zentaur, ``Es gibt niemals einen anderen
Weg.''

``Und ist die Straße zu diesem Garten der indirelte Weg?''

``Oh, sehr sogar, insofern sie beides, Bestimmung und gesunden
Menschenverstand umgeht.''

``Was muss, das muss,'' sagt Jurgen, ``und auf jeden Fall bin ich gewillt,
jeden Trank einmal zu kosten.''

``Du wirst frierem so wie Du reist. Denn Du ind ich, wir werden einen seltsamen
Weg nehmen auf der Suche nach der Gerechtigkeit., über den Graben eines Traumes
hinweg und durch die Tücken der Zeit hindurch. Daher zeihst Du Dir am Besten
dieses Hemd über deine übrige Kleidung.''

``Das ist in der Tat ein feines, glänzendes Kleidungsstück mit seltsamen
Figuren darauf. I nehme ein solches Gewand glücklich entgegen. Und wem soll ich
nun für solche Freundlichkeit danken?''

``Mein Name'', sagte der Zentaur, ``Ist Nessus.''

``Nun dann, Freund Nessus, zu Deinen Diensten.''

Und eins, zwei, drei saß Jurgen auf des Zentauren Rücken, und sie beide hatten
irgendwie die Höhle verlassen und querten Anmerans Heide. So durchqueren sie
eine bewaldete Gegend, in der das Sonnenlicht unerklärlich lange andauerte.
Dann wandte sich der Zentaur nach Westen. Und nun glänzte über den Schultern
des Pfandleihers und auf seiner Brust und an seinen schlanken Armen wie ein
Regenbogen das vielfarbige Hemd von Nessus.

Eine Weile gingen sie durch einen Wald, bestehend aus großen Bäumen die in
einer guten Distanz zueinander standen, wobei des Zentauren güldene Hufe in
einem weichen Teppich aus abgestorbenem Laub versanken, alle grau und braun, in
einer Lage, die von keinem Unterholz unterbrochen wurde. Nun geschah etwas
Unglaubliches, was Jurgen niemals geglaubt hätte, hätte er es nicht mit seinen
eigenen Augen gesehen: Denn nun ging der Zentaus so schnell, dass er ein wenig
gegen die Sonne aufholte, so dass diese im Westen Stückchen für Stückchen
aufging; und sie beide beschleunigten westwärts im Glorienschein eines sich
entfernenden Sonnenuntergangs. Die Sonne fiel in Jurgens Gesicht, als er gerade
nach Westen ritt, so dass er blinzelte und seine Augen schloss, und bald zur
einen, bald zur anderen Seite schaute. So geschah es, dass die Gegend um ihn
herum und die Leute, an denen sie vorbeikamen, von ihm nur in kleinen Blitzen
wahrgenommen wurden, so wie Bilder, die schnell in andere Bilder transformiert
wurden; und alle seine Erinnerungen an diese glänzende Hochstraße waren, in
direkter Konsequenz, immer verworren und unzusammenhängend.

Er wunderte sich, dass so viele junge Frauen die Straße zum Garten entlang
gingen. Hier war ein schlankes Mädchen in Weiß, die ihren braun-gelben Hund
streichelte, der schwerfällig um sie herum sprang; dort saß ein Mädchen in den
Ästen eines verdrehten, knorrigen Baumes, und in ihrem Rücken war ein breiter
schlammiger Fluss, kupferfarben in der Sonne; und hier glänzte das helle Haar
eines großen Mädchens auf dem Rücken eines Pferdes, die auf jemanden zu warten
schien: Kurz gesagt, die Mädchen entlang des Weges waren zahllos, und Jurgen
dachte, dass er eine oder zwei von ihnen wiedererkannte.

Doch der Zentaur ging so flink, dass Jugen sich nicht sicher sein konnte.
