Der Garten zwischen Dämmerung und Morgenröte
--------------------------------------------

So war es, dass Jurgen und der Zentaur zum Garen zwischen Dämmerung und
Morgenröte kamen, einen Ort, den sie auf eine Art erreichten, die nicht
geeignet ist, aufgezeichnet zu werden. Aber als sie die Brücke überquerten,
flohen Drei vor ihnen, schreiend. Und als das Leben aus den kleinen, pelzigen
Körpern getrampelt wurde, die diese Drei okkupiert hatten, blieb niemand,
sich des Zentauren Eintritt in den Garten zwischen Dämmerung und Morgenröte
entgegen zu stellen

Das war ein wundervoller Garten, und nichts darin war seltsam. Stattdessen
schien Jurgen hier alles herzerweichend bekannt und sehr lieblich. Denn er war
zu einem breiten Rasen gekommen der sich nordwärts zu einem Bach seiner
Erinnerung erstreckte, und viele Ahorn- und Affenbrotbäume standen hier und da
unregelmäßig, und in ihren Zweigen spielte unablässig ein leichter Westwind,
so dass das Laub raschelte und fiel wie ein grüner Sprühregen; abder der Herbst
stand vor der Tür, denn die Affenbrotbäume warfen einen Danaerschauer von
kleinen runden Blättern ab. Um den Garten herum war ein unvergessener Kreis von
blauen Bergen. Und das war ein Platz von klarem Zwielicht, nicht errhellt von
Sonne oder Sternen, und mit keinen Schatten irgendwo in dem schwach strahlenden
Licht, dass in diesem Garten erleuchtete, was keinem Menschen sichtbar ist
außer im kurzen Intervall zwischen Dämmerung und Morgenröte.

``Wie, das ist ja Graf Emmericks Garten in Storisende,'' sagt Jurgen, ``in dem
ich so feine Stunden verbracht habe, als ich ein junger Bursche war.''

``Ich will annehmen,'' sagte Nessus, ``dass Du gewöhnlich nicht alleine in diesem Garten spazieren gingst.''

``Nun, nein, es gab da ein Mädchen.''

``Genau so,'' stimmte Nessus zu, ``Es ist ein lokales Naturgesetz: Und hier
sind die, die mit diesem übereinstimmen.''

Denn nun waren zu ihnen getreten, gemeinsam in der Dämmerung spazierend, ein
ansehnlicher Jüngling und ein Mädchen. Und das Mädchen war unglaublich hübsch,
denn jeder im Garten sah sie durch die Augen des jungen Mannes, der mit ihr
zusammen war. ``Ich bin Rudolph,'' sagte der Jüngling, ``und sie ist Anne.''

``Und ihr seid hier glücklich?'' fragte Jurgen.

``Ph ja, Herr, wir sind ziemlich glücklich, aber Annes Vater ist sehr reich,
und meine Mutter ist arm, also können wir nicht sehr glücklich sein, bis ich
nicht in ein fernes Land gegangen bin und mit einer großen Menge von Lakhs
und Rupieen zurückkomme.''

``Und was wirst Du mit dem ganzen Geld machen, Rudolph?''

``Meine Pflicht, mein Herr, wie ich sie sehe, aber ich habe schlechtes
Augenlicht geerbt.''

``Gott sei mit Dir, Rudolph!'' sagte Jurgen. ``Viele andere sind in der
gleichen Lage wie Du.''

Dann kamen zu Jurgen und dem Zentauren ein weitere Junge mit der kleinen,
blauäugigen Person, an der er Gefallen gefunden hatte. Und dieser fette und
träge aussehende Junge informierte sie, dass er und das Mädchen, das bei ihm
war, im Glanz eines roten Senfglases spazierten, was Jurgen für Geschwätz
hielt. Und der Junge sagte, dass er und das Mädchen entschieden hätten,
niemals älter werden wollten, wovon Jurgen sagte, dass das eine ausgezeichnete
Idee sei, wenn sie diese nur umsetzen könnten.

``Oh, I kann das hinkriegen,'' sagte der fette Junge nachdenklich, ``wenn ich
nur nicht herausfinde, dass das Hinkriegen ungemütlich für mich wird.''

``Ich fühle mit Dir,'' sagte Jurgen, ``denn ich stelle fest, dass Du auch ein
monstermäßig cleveres Kerlchen bist: So holst Du das Beste aus dem Leben
heraus.''

``Aber ist Cleverness nicht die Haptsache, mein Herr?''

``Das wird die Zeit Dir zeigen, mein Junge,'' sagte Jurgen etwas sorgenvoll.
``Und Gott sei mit Dir, denn viele andere sind in der gleichen Lage wie Du.''

Und eine Menge weiterer Jungen und Mädchen sah Juergen in dem Garten. Und alle
Gesichter, die Jurgen sah, waren jung und glücklich und sehr lieblich und
herzerweichend zuversichtlich, wie die zahllosen jungen Leute auf Jurgen 
zukamen und an ihm vorbeigingen, im ersten Glühen der Dämmerung; so gingen sie
alle jubelnd in der Blüte ihrer Jugend, voraussehend, dass das Leben ein
winziger Gegenspieler war, von dem man sich mit Leichtigkeit alles nehmen
konnte, was man sich wünschte. Und alle gingen paarweise, ``als ob sie von der
Arche kämen,'' sagte Jurgen. Aber der Zentaur sagte, sie folgten einer Vorgabe,
die weitaus älter als die Arche war.

``Denn in diesem Garten'', sagte der Zentaur, ``hat sich jeder Mann, der
jemals lebte, eine kurze Weile aufgehalten mit keiner Begleitung außer seinen
Illusionen. Ich muss Dir erneut sagen, dass man in diesem Garten nichts außer
imaginären Kreaturen begegnen kann. Und tüchtige Menschen nehem ihre Stunde
der Erholung hier wahr, und sie gehen unbegleitet von hier fort, um Ratsherren
und respektable Kaufleute und Bischöfe zu werden, und um als Hauptleute auf
stolzierenden Pferden bewundert zu werden, oder sogar als Könige auf großen
Thronen; und jeder in seinem Stande denkt nicht mehr an diesen Garten. Aber
ab und zu kommen ängstliche Menschen, Jurgen, die sich fürchten, den Garten
ohne Begleitung zu verlassen: Deshalb müssen diese von hier fort gehen mit der
einen oder anderen imaginären Kreatur, um sie über Gassen und Nebenstraßen zu
führen, denn imaginäre Kreaturen finden wenig Nahrhaftes in den öffentlichen
großen Straßen und meiden sie. Darum müssen sich diese ängstlichen Menschen
versteckt halten mit ihren zaghaften und schreckhaften Wegweisern, und sie
kommen niemals freiwillig auf die gefüllten Plätze, wo Männer Pferde bekommen
und Throne errichten.''

``Und was wird aus diesen ängstlichen Menschen, Zentaur?''

``Nun, manchmal verschwenden sie Papier, Jurgen, und manchmal verschwenden sie
Menschenleben.''

``Dann sind diese verfluchte Menschen,'' stellte Jurgen fest.

``Das solltest Du am Besten wissen,'' antwortete der Zentaur.

``Oh, sehr wahrscheinlich,'' sagte Jurgen. ``Unterdessen ist hier jemand, der
alleine in diesem Garten wandelt, und ich wundere mich, dass die lokalen
Gesetze solcherart verletzt werden.''

Nun schaute Nessus Jurgen eine weile sprachlos an, und in den Augen des
Zentauren war so viel Verständnis und so viel Mitleif, dass es Jurgen
beunruhigte. Denn irgendwie machte es Jurgen unruhig, und er sah es als
unangenehm persönliche Art und Weise an, jemanden anzuschauen.

``Ja, sicher,'' sagte der Zentaur, ``diese Frau wandelt alleine. Aber es gibt
kein Hilfsmittel gegen ihre Einsamkeit, denn der Bursche, der diese Frau
liebte, ist tot.''

``Nessus, ich bin gewillt, einigermaßen mitfühlend darüber zu sein, Aber ist
es wirklich notwendig, ein so unheilvoll langes Gesicht deshalb zu ziehen?
Letzten Endes sind sehr viele andere Menschen gestorben, hin und wieder. Und 
auf jeden Fall kann ich im Gegenteil sagen dass dieser spezielle junge Kerl
vielleicht für niemanden ein so großer Verlust war.''

Und wieder sagte der Zentautr: ``Du solltest es am Besten wissen.''
