Warum Jurgen tat, was ein Mann tun muss
---------------------------------------

Es gibt eine Geschichte, die in Poictesme erzählt wird, die besagt: In den
alten Zeiten lebte ein Pfandleiher namens Jurgen, aber wie seine Frau ihn
nannte, war oft schlimmer als das. Sie war eine übermütige Frau ohne eine
besondere Gabe für die Schweigsamkeit. Ihr Name, sagt man, war Adelais, aber
die Leute nannten sie für gewöhnlich Dame Lisa.

Auch sagen sie, dass in den alten Tagen, nachdem er die Ladenfenster für die
Nacht geschlossen hatte, Jurgen auf seinem Nachhauseweg an der alten
Zisterzienserabtei vorüber kam. Und einer der Mönche stolperte über einen Stein
auf seinem Weg. Er verfluchte den Teufel, der ihn dort hingelegt hatte.

``Pfui, Bruder'', sagt Jurgen, ``Und haben die Teufel nicht schon genug daran
zu tragen, wie es ist?''

``Ich hielt es nie mit Origines.'', antwortete der Mönch, ``Und abgesehen davon
tut mir mein großer Zeh außerordentlich weh.''

``Trotzdem'', bemerkte Jurgen, ``gehört es sich nicht für eine gottesfürchtige
Person, respektlos über den göttlich berufenen Prinz der Dunkelheit zu
sprechen. Zu Deiner weiteren Verwirrung, betrachte das Geschäft dieses
Monarchen. Tag und Nacht magst Du ihn dabei entdecken, sich mit der Aufgabe zu
plagen, die ihm die Heiden auferlegt haben. Das ist eine Sache, die nur von
wenigen Gemeinschaften gesagt werden kann, und schon gar nicht von Mönchen. Und
denke weiters an seine feine Kunstfertigkeit, bewiesen durch die gefährlichen
und lieblichen Fallstricke, die zu bekämpfen Deine Aufgabe, und meine, für sie
Geld zu verleihen ist. Wäre er nicht, hätten wir beide keine
Daseinsberechtigung! Und dann betrachte seine Menschenfreundlichkeit. Und
bedenke, wie unerträglich unser Leben wäre, wären Du und ich und unsere
Gemeindemitglieder mit anderen Bestien heute schon auf Du und Du in dem Garten,
von dem wir vorgebenm ihn für die Sonntage zu ersehnen! Aufstehen mit den
Schweinen und sich niederlegen mit den Hyänen? Oh, nicht auszudenken!''

So fuhr er fort Gründe anzuführen, nicht zu streng vom Teufel zu denken. Die
meisten waren Abwandlungen einiger Verse, die Jurgen komponiert hatte, in
seinem Laden, wenn das Geschäft ausblieb.

``Ich betrachte dieses als Unfug und Nonsens,'' war die Abtwort des Mönchs.

``Kein Zweifel, dass Deine Anschauung verständlich ist,'' bemerkte der
Pfandleiher, ``aber meine ist die Schönere.''

Dann war Jurgen an der Zisterzienserabtei vorbei und näherte sich Bellegarde,
als ihm ein schwarzer Herrn begegnete, der ihn grüßte und sagte: ``Danke,
Jurgen, für Dein gutes Wort.''

``Wer bist Du, und wofür dankst Du mir?'' fragte Jurgen.

``Mein Name tut nichts zur Sache. Aber Du hast ein freundliches Herz, Jurgen.
Möge Dein Leben frei von Sorge sein.''

``Bewahre uns vor Schmerz und Schaden, mein Freund, aber ich bin schon
verheiratet.''

``Ja, sicher, ein feiner cleverer Poet wie Du!''

``Aber es ist eine Weile her, dass ich ein parktizierender Poet war.''

``Nun, ich will ehrlich sein! Du hast das künstlerische Temperament, das nicht
gerade geschaffen ist für die Einschränkungen des häuslichen Lebens. Und ferner
nehme ich an, dass Dein Weib ihre ganz eigene Meinung von Poesie hat, Jurgen.''

``In der Tat, mein Herr, ihre Meinung wieder zu geben, ist untragbar, da ich
sicher bin, dass Sie eine solche Sprache nicht gewohnt sind.''

``Das ist sehr traurig. Ich fürchte, Dein Weib versteht Dich nicht richtig,
Jurgen.''

``Mein Herr,'' sagte Jurgen erstaunt, ``lesen Sie der Menschen innerste
Gedanken?''

Der schwarze Herr schien sehr niedergeschlagen. Er schürzte die Lippen, begann,
an seinen Fingern etwas abzuzählen. Als sie sich bewegten, flackerten seine
scharfen Fingernägel wie Flammenpunkte.

``Nun, das ist eine sehr Bedauerliche Tatsache,'' sagte der schwarze Herr,
``die der ersten Person widerfahren ist, die ich kennengelernt habe, und die
ein freundliches Wort für das Böse eingelegt hat. Und das nach all den
Jahrhunderten! Ich Armer, das ist eine so bedauernswertes Vorkommnis eines
Missmanagements! Aber keine Sorge, Jurgen, der Morgen ist heller als der Abend.
Ich werde Dich belohnen, sei dessen gewiss!''

Also dankte Jurgen der einfachen alten Gestalt höflich. Und als Jurgen sein
Heim erreichte, war seine Frau nirgends zu sehen. Er schaute in allen Winkeln
nach und befragte jeden, aber vergeblich. Dame Lisa war verschwunden, mitten in
der Zubereitung des Abendessens, plötzlich, vollständig und unerklärlich.,
gerade wie (in Jurgens Geschichten) ein Windsturm vorüber geht und eine Ruhe
hinterlässt, die durch den Kontrast unheimlich wirkt. Nichts konnte dieses
Geheimnis erklären außer Magie: Und plätzlich erinnerte sich Jurgen des
schwarzen Herrn seltsamen Versprechens. Jurgen bekreuzigte sich.

``Wie ungerecht'' sagt Jurgen, ``bekommen einige Leute einen schlechten Ruf
für ihre Dankbarkeit! Und ich erkenne nun, wie weise es von mir ist, immer
freundlich von jedem zu sprechen, in dieser Welt voller Schwätzer.''

Dann bereite Jurgen sein eigenes Abendessen, ging zu Bett und schlief tief und
fest.

``Ich habe vollstes Vertrauen'' sagt er, ``in Lisa. Ich habe besonderes
Vertrauen, dass sie in jeder Umgebung klarkommt.''

Das war alles schön und gut, aber die Zeit verging, und bald ging das Gerücht,
dass Dame Lisa auf Morven umging. Ihr Bruder, der ein Gemüsehändler und
Mitglied des Stadtrates war, ging dorthin, um diesen Bericht zu prüfen. Und
sicher genug, dort wandelte Jurgens Frau im Zwielicht und murrte ohne
Unterlass.

``Pfui, Schwester,'' sagte der Stadtrat, ``das ist ein unziemliches Benehmen
für eine verheiratete Frau, und eine Sache, über die sicher geredet wird.''

``Folge mir!'', antwortete Dame Lisa. Und der Stadtrat fpögte ihr ein Stück
weit in die Dämmerung, aber als sie auf die Amneran Heide kamen und immer
weitergingen, wusste er Besseres, als ihr zu folgen.

Am nächsten Abend ging die ältere Schwester von Dame Lisa nach Morven. Diese
Schwester hatte einen Notar geehelicht und war eine gewitzte Frau. Deshalb
nahm sie an diesem Abend einen langen Stecken von geschältem Weidenholz mit.
Und dort wandelte Jurgens Frau im Zwielicht und murrte ohne Unterlass.

``Pfui, Schwester!'', sagte des Notars Weib, die eine gewitzte Frau war, ``und
weißt Du nicht, dass unterdessen Jurgen sein eigenes Spiel treibt und wieder
einmal Komtess Dorothy schöne Augen macht?''

Dame Lisa schauderte, doch sie sagte nur: ``Folge mir!''

Und des Notars Weib folgte ihr zur Anmeran Heide, und über die Heide hinaus zu
einem Ort, an dem sich eine Höhle befand. Das war ein Platz von abscheulichem
Ruf. Ein magerer Hund kam, um sie im Zwielicht zu treffen, die Zunge
heraushängend. Doch des Notars Weib schlug dreimal mit ihrem Stecken, und die
stille Bestie verließ sie. Und Dame Lisa ging still in die Höhle, und ihre
Schwester wandte sich um und ging weinend heim zu ihren Kindern.

So kam am nächsten Abend Jurgen selbst nach Morven, denn seines Weibs Familie
versicherte ihm, das sei das, was ein Mann tun musste. Jurgen überließ
den Laden der Obhut von Urien Villemarche, der ein sehr effizienterAngestellter
war. Jurgen folgte seinem Weib über Anmeran Heide bis sie die Höhle erreichten.
Jurgen wäre freiwillig gerne woanders.

Denn der Hund setzte sich auf seine Hinterbeine und schien Jurgen anzugrinsen,
und es waren andere Kreaturen um sie herum, die tief im Zwielicht umherflogen,
sich wie Eulen nahe am Boden haltend. Aber sie waren größer als Eulen und sie
waren unbehaglicher. Darüberhinaus war es gerade nach Sonnenuntergang von
Walpurgisnacht, wenn fast alles passieren kann.

Also sagte Jurgen, ein wenig verdreißlich: ``Lisa, meine Liebe, wenn Du in die
Höhle hegst, werde ich Dir folgen müssen, denn das ist das, was ein Mann tun
muss. Und Du weißt, wie leicht ich mir eine Erkältung zuziehe.''

Die Stimme von Dame Lisa war nun dünn und klagend, eine seltsam verwandelte
Stimme. ``Da ist ein Kreuz um Deinen Hals. Du musst das wegwerfen.''

Jurgen trug ein solches Kreuz aus sentimentalen Gründen, denn es hatte einst
seiner verstorbenen Mutter gehört. Aber nun, um seiner Frau zu Gefallen zu
sein, entfernte er das Schmuckstück und hing es an einen Berberitzenbusch, und
mit der Überlegung, dass dieses ein bedauerliches Unterfangen sei, folgte er
Dame Lisa in die Höhle.
